version: '3.1'

services:    
  apache-php:
    image: wsfeitosa/apache-php-ssl    
    build:
      context: ./app
    container_name: apache-php-ssl    
    restart: always    
    volumes:      
      - D:\Docker\scoa\gerenciador_contas_sap:/var/www/html:rw
    networks:
      - portal-allink    
    ports:
      - 8090:80
      - 8091:443
    expose:
      - "80"
      - "443"
    
networks:
  portal-allink:
    driver: bridge